# Generated by Django 4.0.5 on 2022-06-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='car',
            name='name',
            field=models.CharField(default='Test', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='car',
            name='year',
            field=models.IntegerField(default=2004),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='engine',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='make',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
